### ISSUE TITLE
Demo http://www.e-kaifa.com/projects/mybloh/kanbans Server crashed

### ISSUE THREAD

**Issue by cforce** [samchen2009/ekanban#1]
Ruby (Rack) application could not be started
A source file that the application requires, is missing.
It is possible that you didn't upload your application files correctly. Please check whether all your application files are uploaded.
A required library may not installed. Please install all libraries that this application requires.
Further information about the error may have been written to the application's log file. Please check it in order to analyse the problem.
Error message:
Please install the sqlite3 adapter: `gem install activerecord-sqlite3-adapter` (sqlite3 is not part of the bundle. Add it to Gemfile.)
Exception class:
LoadError
Application root:
/home/shchen/work/myredmine
Backtrace:
# File    Line    Location

0   /usr/local/rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.1/lib/bundler/rubygems_integration.rb  147 in `block in replace_gem'
1   /usr/local/rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.8/lib/active_record/connection_adapters/sqlite3_adapter.rb    3   in`'
2   /usr/local/rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.8/lib/active_support/dependencies.rb 251 in `require'
3   /usr/local/rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.8/lib/active_support/dependencies.rb 251 in`block in require'
4   /usr/local/rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.8/lib/active_support/dependencies.rb 236 in `load_dependency'
5   /usr/local/rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.8/lib/active_support/dependencies.rb 251 in`require'
6   /usr/local/rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_specification.rb

**Comment by samchen2009** [comment]
Sorry, it crashed at setup heroku push, now it's fixed.
