### ISSUE TITLE
After setting up Kanban for project, the kanban view page throws error

### ISSUE THREAD

**Issue by sheldonshi** [samchen2009/ekanban#10]
Redmine 2.2.3. The latest ekanban clone. Here is the log:

Started GET "/redmine/projects/test-performance/kanbans" for 50.150.73.169 at 2013-03-18 01:18:58 +0000
Processing by KanbansController#index as HTML
  Parameters: {"project_id"=>"test-performance"}
  Current user: user (id=1)
  Rendered plugins/ekanban/app/views/kanbans/index.html.haml within layouts/base (8.6ms)
Completed 500 Internal Server Error in 30ms

ActionView::Template::Error (undefined method `id' for nil:NilClass):
    2:   %span Your current wip:
    3:   = link_to "#{User.current.wip} ", my_page_path(), :id => "my-wip"
    4:   %span  Limit:
    5:   = link_to "#{User.current.wip_limit} ", edit_user_path(User.current.id), :id => "my-wip-limit"
    6:   = link_to l(:label_kanban_new), new_project_kanban_path(@project.id), :class => 'icon icon-add'
    7: %h2 Kanbans
    8: 
  plugins/ekanban/app/models/kanban.rb:283:in`wip_limit'
  plugins/ekanban/app/views/kanbans/index.html.haml:5:in `_plugins_ekanban_app_views_kanbans_index_html_haml___698950943912935785_70055118203060'
  actionpack (3.2.12) lib/action_view/template.rb:145:in`block in render'
  activesupport (3.2.12) lib/active_support/notifications.rb:125:in `instrument'
...

**Comment by abagiev** [comment]
Hi, I've also seen this issue with latest master clone after resolved #5.
Redmine 2.2.3.

**Comment by samchen2009** [comment]
The error meant that it cannot find a "WIP Limit" field in the customField table, which is added by ekanban plugin, did you "rake redmine:plugins:migrate" ?

**Comment by jlestel** [comment]
Hi, I don't find this entry in the "custom_field" table. But i execute "rake redmine:plugins:migrate" and i can see all tables related to your plugin.

**Comment by jlestel** [comment]
I added manually "WIP Limit" field in User custom fields and it resolve this bug.

**Comment by sheldonshi** [comment]
Yes I ran "rake redmine:plugins:migrate" and it executed without an error. I have to manually add "WIP Limit" as jlestel said to make it work.

**Comment by samchen2009** [comment]
Oops... My fault, I totally forget about this, Yes, you need to add "WIP Limit" in Administrator -> Custom fields -> User. Will update the document.
