### ISSUE TITLE
project settings page = 404 error

### ISSUE THREAD

**Issue by chupacabras** [samchen2009/ekanban#12]
i have installed this plugin but when i want to show project settings page, i get error 404:
"The page you were trying to access doesn't exist or has been removed."

log contains:
Started GET "/redmine/projects/projectx/settings" for 192.168.1.7 at Tue Mar 19 16:08:17 +0100 2013
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"projectx"}
  Current user: duro (id=8)
  Rendered projects/_form.html.erb (82.0ms)
  Rendered projects/_edit.html.erb (99.9ms)
  Rendered projects/settings/_modules.html.erb (288.0ms)
  Rendered projects/settings/_members.html.erb (851.3ms)
  Rendered projects/settings/_versions.html.erb (31.9ms)
  Rendered projects/settings/_issue_categories.html.erb (259.8ms)
  Rendered projects/settings/_wiki.html.erb (9.7ms)
  Rendered projects/settings/_repositories.html.erb (16.9ms)
  Rendered projects/settings/_boards.html.erb (15.6ms)
  Rendered projects/settings/_activities.html.erb (342.7ms)
  Rendered plugins/ekanban/app/views/common/_tabs.html.erb (2016.0ms)
  Rendered projects/settings.html.erb within layouts/base (3707.7ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (1.3ms)
Completed 404 Not Found in 3987ms (Views: 118.5ms | ActiveRecord: 58.8ms)

Environment:
  Redmine version                          2.1.4.stable
  Ruby version                             1.8.7 (x86_64-linux)
  Rails version                            3.2.8
  Environment                              production
  Database adapter                         PostgreSQL
Redmine plugins:
  AgileDwarf                               0.0.3
  ekanban                                  0.0.1
  redmine_inline_attach_screenshot         0.4.2
  redmine_people                           0.1.6
  stuff_to_do_plugin                       0.4.1

**Comment by chupacabras** [comment]
I forgot to install "haml".
Now it seems to work.

**Comment by fk0** [comment]
Despite this issue is closed I'd like to mention that ekanban does not work with haml 4.0.3 (at least this one version). I received exactly the same error as stated in this issue. The solution was not quick but is easy though - just remove haml 4.0.3 and install 3.1.8. Then do uninstall for ekanban and install it again (it's strange but finally I had to perform db:migrate twice upon install)

```
gem uninstall haml -v "4.0.3"
gem install haml -v "3.1.8"
rake redmine:plugins:migrate NAME=ekanban VERSION=0 RAILS_ENV=production
rake redmine:plugins:migrate --trace RAILS_ENV=production
```
