### ISSUE TITLE
kanban page throws error 500

### ISSUE THREAD

**Issue by chupacabras** [samchen2009/ekanban#13]
when i want to display "kanban" page i get error 500.

log:
Started GET "/redmine/projects/projectx/kanbans" for 192.168.1.7 at Tue Mar 19 16:26:24 +0100 2013
Processing by KanbansController#index as HTML
  Parameters: {"project_id"=>"projectx"}
  Current user: duro (id=8)
  Rendered plugins/ekanban/app/views/kanbans/index.html.haml within layouts/base (7.4ms)
Completed 500 Internal Server Error in 71ms

ActionView::Template::Error (undefined method `require_relative' for main:Object):
    1: .contextual
    2:   %span Your current wip:
    3:   = link_to "#{User.current.wip} ", my_page_path(), :id => "my-wip"
    4:   %span  Limit:
    5:   = link_to "#{User.current.wip_limit} ", edit_user_path(User.current.id), :id => "my-wip-limit"
    6:   = link_to l(:label_kanban_new), new_project_kanban_path(@project.id), :class => 'icon icon-add'
  plugins/ekanban/app/models/kanban_card.rb:1
  activesupport (3.2.8) lib/active_support/dependencies.rb:251:in`require'
  activesupport (3.2.8) lib/active_support/dependencies.rb:251:in `require'
  activesupport (3.2.8) lib/active_support/dependencies.rb:236:in`load_dependency'
  activesupport (3.2.8) lib/active_support/dependencies.rb:251:in `require'
  activesupport (3.2.8) lib/active_support/dependencies.rb:359:in`require_or_load'
  activesupport (3.2.8) lib/active_support/dependencies.rb:502:in `load_missing_constant'
  activesupport (3.2.8) lib/active_support/dependencies.rb:192:in`const_missing'
  activesupport (3.2.8) lib/active_support/dependencies.rb:190:in `each'
  activesupport (3.2.8) lib/active_support/dependencies.rb:190:in`const_missing'
  activesupport (3.2.8) lib/active_support/dependencies.rb:514:in `load_missing_constant'
  activesupport (3.2.8) lib/active_support/dependencies.rb:192:in`const_missing'
  activesupport (3.2.8) lib/active_support/dependencies.rb:190:in `each'
  activesupport (3.2.8) lib/active_support/dependencies.rb:190:in`const_missing'
  plugins/ekanban/app/models/kanban.rb:279:in `wip'
  plugins/ekanban/app/views/kanbans/index.html.haml:3:in`_plugins_ekanban_app_views_kanbans_index_html_haml__997719695_70242965774420'
  actionpack (3.2.8) lib/action_view/template.rb:145:in `send'
  actionpack (3.2.8) lib/action_view/template.rb:145:in`render'
  activesupport (3.2.8) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.8) lib/action_view/template.rb:143:in`render'
  actionpack (3.2.8) lib/action_view/renderer/template_renderer.rb:47:in `render_template'
  actionpack (3.2.8) lib/action_view/renderer/abstract_renderer.rb:38:in`instrument'
  activesupport (3.2.8) lib/active_support/notifications.rb:123:in `instrument'
  activesupport (3.2.8) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.8) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.8) lib/action_view/renderer/abstract_renderer.rb:38:in`instrument'
  actionpack (3.2.8) lib/action_view/renderer/template_renderer.rb:46:in `render_template'
  actionpack (3.2.8) lib/action_view/renderer/template_renderer.rb:54:in`render_with_layout'
  actionpack (3.2.8) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
  actionpack (3.2.8) lib/action_view/renderer/template_renderer.rb:18:in`render'
  actionpack (3.2.8) lib/action_view/renderer/renderer.rb:36:in `render_template'
  actionpack (3.2.8) lib/action_view/renderer/renderer.rb:17:in`render'
  actionpack (3.2.8) lib/abstract_controller/rendering.rb:110:in `_render_template'
  actionpack (3.2.8) lib/action_controller/metal/streaming.rb:225:in`_render_template'
  actionpack (3.2.8) lib/abstract_controller/rendering.rb:103:in `render_to_body'
  actionpack (3.2.8) lib/action_controller/metal/renderers.rb:28:in`render_to_body'
  actionpack (3.2.8) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
  actionpack (3.2.8) lib/abstract_controller/rendering.rb:88:in`render'
  actionpack (3.2.8) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:40:in`render'
  activesupport (3.2.8) lib/active_support/core_ext/benchmark.rb:5:in `ms'
  /usr/lib/ruby/1.8/benchmark.rb:308:in`realtime'
  activesupport (3.2.8) lib/active_support/core_ext/benchmark.rb:5:in `ms'
  actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:40:in`render'
  actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
  activerecord (3.2.8) lib/active_record/railties/controller_runtime.rb:24:in`cleanup_view_runtime'
  actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:39:in `render'
  actionpack (3.2.8) lib/action_controller/metal/implicit_render.rb:10:in`default_render'
  actionpack (3.2.8) lib/action_controller/metal/mime_responds.rb:196:in `respond_to'
  plugins/ekanban/app/controllers/kanbans_controller.rb:74:in`index'
  actionpack (3.2.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.8) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
  actionpack (3.2.8) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.8) lib/action_controller/metal/rendering.rb:10:in`process_action'
  actionpack (3.2.8) lib/abstract_controller/callbacks.rb:18:in `process_action'
  activesupport (3.2.8) lib/active_support/callbacks.rb:458:in`_run__1479901434__process_action__1121113129__callbacks'
  activesupport (3.2.8) lib/active_support/callbacks.rb:405:in `send'
  activesupport (3.2.8) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.8) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.8) lib/active_support/callbacks.rb:81:in`send'
  activesupport (3.2.8) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.8) lib/abstract_controller/callbacks.rb:17:in`process_action'
  actionpack (3.2.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:30:in`process_action'
  activesupport (3.2.8) lib/active_support/notifications.rb:123:in `instrument'
  activesupport (3.2.8) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.8) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
  actionpack (3.2.8) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.8) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  actionpack (3.2.8) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.8) lib/abstract_controller/rendering.rb:45:in`process'
  actionpack (3.2.8) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.8) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  actionpack (3.2.8) lib/action_controller/metal.rb:246:in `action'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:73:in`call'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:36:in`call'
  journey (1.0.4) lib/journey/router.rb:68:in `call'
  journey (1.0.4) lib/journey/router.rb:56:in`each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:600:in`call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  rack (1.4.1) lib/rack/etag.rb:23:in `call'
  rack (1.4.1) lib/rack/conditionalget.rb:25:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.1) lib/rack/session/abstract/id.rb:205:in`context'
  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/cookies.rb:339:in`call'
  activerecord (3.2.8) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
  activesupport (3.2.8) lib/active_support/callbacks.rb:405:in`_run__253107497__call__4__callbacks'
  activesupport (3.2.8) lib/active_support/callbacks.rb:405:in `send'
  activesupport (3.2.8) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.8) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.8) lib/active_support/callbacks.rb:81:in`send'
  activesupport (3.2.8) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.8) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.8) lib/rails/rack/logger.rb:26:in`call_app'
  railties (3.2.8) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/request_id.rb:22:in`call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.1) lib/rack/runtime.rb:17:in`call'
  activesupport (3.2.8) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.1) lib/rack/lock.rb:15:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/static.rb:62:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.8) lib/rails/engine.rb:479:in `call'
  railties (3.2.8) lib/rails/application.rb:223:in`call'
  railties (3.2.8) lib/rails/railtie/configurable.rb:30:in `send'
  railties (3.2.8) lib/rails/railtie/configurable.rb:30:in`method_missing'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_request_handler.rb:513:in`accept_and_process_next_request'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/classic_rails/application_spawner.rb:321:in`start_request_handler'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `send'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/classic_rails/application_spawner.rb:275:in`handle_spawn_application'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/utils.rb:479:in `safe_fork'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/classic_rails/application_spawner.rb:270:in`handle_spawn_application'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server.rb:357:in `__send__'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server.rb:180:in `start'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/classic_rails/application_spawner.rb:149:in`start'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server_collection.rb:132:in`lookup_or_add'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server_collection.rb:82:in`synchronize'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/spawn_manager.rb:213:in`spawn_rails_application'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/spawn_manager.rb:275:in`handle_spawn_application'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server.rb:357:in `__send__'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  /usr/lib/ruby/gems/1.8/gems/passenger-3.0.12/helper-scripts/passenger-spawn-server:99

**Comment by jlestel** [comment]
I added manually "WIP Limit" field in User custom fields to resolve this bug.

**Comment by chupacabras** [comment]
Nope. It did not help.
And I think custom fields have nothing to do with error I posted.

It seems that this plugin requires ruby 1.9, but we are running 1.8

**Comment by chupacabras** [comment]
I replaced line
require_relative "kanban.rb"
to
require File.join(File.dirname(**FILE**), 'kanban.rb')
in file kanban_card.rb
and solved this problem.

**Comment by samchen2009** [comment]
Yes, I always run it with ruby 1.9.3. Good to hear it got fixed.
