### ISSUE TITLE
Can't delete an entry from the Kanban Panes

### ISSUE THREAD

**Issue by sheldonshi** [samchen2009/ekanban#14]
I created 6 kanban panes for a project. Then I decided to delete one of them. I clicked the "Delete" button in the kanban pane list table. It asked for confirmation, and the page refreshed. The entry was not deleted.

**Comment by samchen2009** [comment]
Fixed in https://github.com/samchen2009/ekanban/commit/7c83bf4dcf0f5651d7f526c8f45729e6b8288673, please verify. Thanks!
