### ISSUE TITLE
500 Internal Server Error when try create a new issue

### ISSUE THREAD

**Issue by jhoanir** [samchen2009/ekanban#22]
When I'm  trying to create a new issue, just get Internal Error message

Completed 500 Internal Server Error in 735ms

NameError (undefined local variable or method `new_pane' for #<Issue:0x7f5528e69090>):
  app/controllers/issues_controller.rb:141:in`create'

**Comment by Mirnoth** [comment]
I have got the same Issue

Completed 500 Internal Server Error in 369ms

NameError (undefined local variable or method `new_pane' for #<Issue:0x7f8f0a16f878>):
  app/controllers/issues_controller.rb:143:in`create'

Info:
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
redmine git version

**Comment by samchen2009** [comment]
A stupid error, fixed by Mirnoth, Thanks!
