### ISSUE TITLE
Completed 500 Internal Server Error in 1707ms

### ISSUE THREAD

**Issue by lourdesh** [samchen2009/ekanban#25]
We install the plugin with Redmine version 2.1.5 and db PostgreSql. After creating panes, states and define the kanban workflow for a project occurs the error listed below.
Does anyone have a hint to solve this problem?
## Thanks.

Completed 500 Internal Server Error in 1707ms

ActionView::Template::Error (undefined method `name' for nil:NilClass):
    28:                     %a
    29:                       %span.ui-icon.ui-icon-minus.menu-icon{:title=>"Collapse All"}
    30:                       .menu-text Collapse All
    31:                   - if KanbanWorkflow.transition_allowed?(s[:states].first,KanbanState.close_state(kanban),kanban.id)
    32:                     %li{:id=>"li_check_all_#{s[:panes].first.id}"}
    33:                       %a
    34:                         %span.ui-icon.ui-icon-check.menu-icon{:title=>"Check All"}
  plugins/ekanban/lib/ekanban/user_patch.rb:26:in`has_role?'
  plugins/ekanban/app/models/kanban_workflow.rb:14:in `transition_allowed?'
  plugins/ekanban/app/views/kanbans/_kanban_board.html.haml:31:in`_plugins_ekanban_app_views_kanbans__kanban_board_html_haml___63318756_70055968030880'
  plugins/ekanban/app/views/kanbans/_kanban_board.html.haml:17:in `each'
  plugins/ekanban/app/views/kanbans/_kanban_board.html.haml:17:in`_plugins_ekanban_app_views_kanbans__kanban_board_html_haml___63318756_70055968030880'
  actionpack (3.2.8) lib/action_view/template.rb:145:in `send'
  actionpack (3.2.8) lib/action_view/template.rb:145:in`render'
  activesupport (3.2.8) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.8) lib/action_view/template.rb:143:in`render'
  actionpack (3.2.8) lib/action_view/renderer/partial_renderer.rb:351:in `collection_with_template'
  actionpack (3.2.8) lib/action_view/renderer/partial_renderer.rb:348:in`each'
  actionpack (3.2.8) lib/action_view/renderer/partial_renderer.rb:348:in `collection_with_template'
  actionpack (3.2.8) lib/action_view/renderer/partial_renderer.rb:250:in`render_collection'
  actionpack (3.2.8) lib/action_view/renderer/partial_renderer.rb:234:in `render'
  actionpack (3.2.8) lib/action_view/renderer/abstract_renderer.rb:38:in`instrument'
  activesupport (3.2.8) lib/active_support/notifications.rb:123:in `instrument'
  activesupport (3.2.8) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.8) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.8) lib/action_view/renderer/abstract_renderer.rb:38:in`instrument'
  actionpack (3.2.8) lib/action_view/renderer/partial_renderer.rb:233:in `render'
  actionpack (3.2.8) lib/action_view/renderer/renderer.rb:41:in`render_partial'
  actionpack (3.2.8) lib/action_view/renderer/renderer.rb:15:in `render'
  actionpack (3.2.8) lib/action_view/helpers/rendering_helper.rb:24:in`render_without_haml'

**Comment by samchen2009** [comment]
Ah, it should occur at 

role = Role.to_role(role)
return true if (role.name == "Anonymous" or role.name == "Non member") 

the output 'role' is nil while input 'role' is "Manager".  You may need to check whether you have a "Manager" role in your setting?: I hard code "Manager" somewhere.

**Comment by samchen2009** [comment]
Could you have a try?
