### ISSUE TITLE
Highlight ekanban tab when it is the currently selected tab

### ISSUE THREAD

**Issue by MischaTheEvil** [samchen2009/ekanban#26]
As reported over at http://www.redmine.org/boards/3/topics/37638:

> I have installed the ekanban plugin and all seems just fine except that when I select (click) on the ekanban tab in a project it does not show as highlighted.
> When you hover over the tab it highlights like all the others. It's just that it does not change color and style when it is the current tab.
> I verified this behavior is regardless of what Theme is in use. It's like they all do not know what to do with that tab.

Without actually testing the plugin but with a quick scan of the code of it, it seems the kanbans controller is missing the `menu_item :ekanban` declaration inside `class KanbansController < ApplicationController` and after the `unloadable` declaration.

Reference: http://www.redmine.org/projects/redmine/repository/entry/trunk/extra/sample_plugin/app/controllers/example_controller.rb#L7

**Comment by samchen2009** [comment]
Thanks a lot !  I'll add it.

**Comment by innocentliny** [comment]
Will this fix be released in next version?
