### ISSUE TITLE
Mysql::Error: Table 'redmine_development.users' doesn't exist

### ISSUE THREAD

**Issue by MarcoAbi** [samchen2009/ekanban#33]
env: turnkey linux  redmine distro, debian wheezy, 64bit

the following command:
"rake redmine:plugins:migrate" 
fails with the following trace:

*\* Invoke redmine:plugins:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
Mysql::Error: Table 'redmine_development.users' doesn't exist: SHOW FULL FIELDS FROM `users`
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `query'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in`execute'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `log'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in`execute'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/connection_adapters/mysql_adapter.rb:324:in `execute_and_free'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:424:in`columns'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/connection_adapters/schema_cache.rb:12:in `initialize'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:228:in`call'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:228:in `default'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:228:in`[]'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:228:in `columns'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:237:in`columns_hash'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/inheritance.rb:19:in `descends_from_active_record?'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/inheritance.rb:25:in`finder_needs_type_condition?'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/base.rb:455:in `relation'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/scoping/named.rb:37:in`scoped'
/usr/local/lib/ruby/gems/1.8/gems/activerecord-3.2.12/lib/active_record/querying.rb:9:in `order'
/var/www/redmine/app/models/group.rb:32
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:469:in`load'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:469:in `load_file'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:639:in`new_constants_in'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:468:in `load_file'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:353:in`require_or_load'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:502:in `load_missing_constant'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:192:in`const_missing'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:190:in `each'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:190:in`const_missing'
/var/www/redmine/plugins/ekanban/init.rb:51:in `_callback_before_5'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:429:in`_run__119331823__prepare__4__callbacks'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `send'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in`__run_callback'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in`send'
/usr/local/lib/ruby/gems/1.8/gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/lib/ruby/gems/1.8/gems/actionpack-3.2.12/lib/action_dispatch/middleware/reloader.rb:74:in`prepare!'
/usr/local/lib/ruby/gems/1.8/gems/actionpack-3.2.12/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/application/finisher.rb:47
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/initializable.rb:30:in`instance_exec'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/initializable.rb:30:in `run'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/initializable.rb:55:in`run_initializers'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/initializable.rb:54:in `each'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/initializable.rb:54:in`run_initializers'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/application.rb:136:in `initialize!'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/railtie/configurable.rb:30:in`send'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/www/redmine/config/environment.rb:14
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/application.rb:103:in`require'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/application.rb:103:in `require_environment!'
/usr/local/lib/ruby/gems/1.8/gems/railties-3.2.12/lib/rails/application.rb:297:in`initialize_tasks'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:246:in`execute'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:241:in`execute'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:184:in `invoke_with_call_chain'
/usr/local/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:205:in`invoke_prerequisites'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:203:in `each'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:203:in`invoke_prerequisites'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:183:in `invoke_with_call_chain'
/usr/local/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/task.rb:170:in`invoke'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:101:in`top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:101:in`top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:95:in`top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:73:in `run'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:160:in`standard_exception_handling'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/usr/local/lib/ruby/gems/1.8/gems/rake-10.0.4/bin/rake:33
/usr/local/bin/rake:19:in`load'
/usr/local/bin/rake:19
Tasks: TOP => redmine:plugins:migrate => environment

**Comment by prmartinuk** [comment]
The documentation probably should be changed to use the command that Redmine recommends for installing and migrating plugins.

Try running the command "rake redmine:plugins:migrate RAILS_ENV=production"
(or change production to whatever Rails environment you are using).

If you don't specify the Rails environment then it will use the default environment, which is rarely the one you really want to use. I think in your case the default Rails environment (which is probably Development) doesn't have Redmine set up on it.

**Comment by MarcoAbi** [comment]
Thanks a lot! 
It works!

all the best

Marco
