### ISSUE TITLE
ajax calls to kanban_apis have hardcoded urls

### ISSUE THREAD

**Issue by klausmeyer** [samchen2009/ekanban#41]
our redmine is installed to a subfolder "https://ssl.example.com/redmine/", so the hardcoded urls in https://github.com/samchen2009/ekanban/blob/master/assets/javascripts/kanban_api.js#L5 are not working.

**Comment by prmartinuk** [comment]
+1

I worked around it by using the webserver's URL rewriting (mapping /kanban_apis to /redmine/kanban_apis), but it would be good to have a proper solution.

**Comment by klausmeyer** [comment]
@prmartinuk yes, this is the way i'm doing it at the moment too :)

**Comment by banterCZ** [comment]
Just a comment how rewrite is done.

Add following code to `redmine-2.3.x-y/apps/redmine/conf/httpd-app.conf`

```
RewriteEngine On
RewriteRule /kanban_apis /redmine/kanban_apis [R]
```
