### ISSUE TITLE
Not seeing 'edit KanBan card' (bitnami Redmine 2.3.2)

### ISSUE THREAD

**Issue by SteveDavis** [samchen2009/ekanban#46]
I have installed The bitnami Redmine 2.3.2 install into a Windows environment and added in your plugin.

The plugin has been configured and I can see the KanBan tab and issues on it.

However, when I look at the demo site, if I try to drag an issue from one phase to another, I see an 'Edit kanban card' window which shows various details of the item (presumably so that comments can be added and the item re-assigned).

But when I do the same on our installation, the item simply drags and drops, with no message. I don't see the window stating (as on the demo site)  "Are you sure? Click 'OK' will update the moving to server" (which is pretty horrible English grammer by the way).

Is the demo site showing work in progress which has not yet been released? Or is this indicative of another issue caused by the Bitnami installation I wonder? I'm not seeing any indication of problems in the production log file.

Bitnami Install Package 2.3.2-1:
- Redmine 2.3.2
- Apache 2.4.6
- ImageMagick 6.5.6-8-Q8
- MySQL 5.5.32
- Subversion 1.7.5
- Git 1.8.3
- Ruby 1.9.3-p231-i386-mingw32
- Rails 3.2.14
- RubyGems 1.8.12

Running on Windows Server 2008 R2.

Any help very much appreciated!

**Comment by prmartinuk** [comment]
Have you got Redmine running in a subfolder (e.g. http://www.example.com/Redmine )?

Due to issue #41, I had exactly the issue you describe because I had Redmine in a subfolder. You can workaround it by using the webserver's URL rewriting (mapping /kanban_apis to /redmine/kanban_apis).

**Comment by SteveDavis** [comment]
Great, Thanks - I didn't previously realise that issue was describing what I was seeing (#41 describes the technical issue, but not the symptoms you see as a result). Have made the same change and it is now working as expected. Thanks for your very quick response on this - Much Appreciated!

**Comment by banterCZ** [comment]
I have fixed it with url rewrite, so I am able to double click to edit. But I see loading bar all the time. More over drag and drop seemingly works but the confirm does not appear.

Using bitnami redmine-2.3.3-0, ubuntu 64bit

**Comment by SteveDavis** [comment]
@banterCZ - Interesting - I experienced this too - and after a lot of trial and error I worked out that one of the other plugins (ElasticSearch) was causing the issue - as soon as I install it, I see what you describe. Remove it and it all works again. As for why exactly.... No idea at this stage. But I thought people might like to know. We're running a windows environment btw.
