### ISSUE TITLE
404 errors in Kanban states and projects Configuration 

### ISSUE THREAD

**Issue by jlestel** [samchen2009/ekanban#5]
Hello, i run Redmine 2.2.3 with the first version of your plugin.

When i try to go on "Administration -> Kanban States", i've a got a 404 error.

This is the same when i select a project and try to open "Configuration" tab.

Thanks you.

**Comment by samchen2009** [comment]
I didn't run it on 2.2.3 yet, I'll have a try and get back to you later.

**Comment by kewinwang** [comment]
I meet this problem on 2.2.3  too

**Comment by samchen2009** [comment]
I can run it on 2.2.3 well. I guess you didn't install "haml" gem, all the templates in ekanban are written by haml. I'll update the README.

**Comment by jlestel** [comment]
I install "haml" gem (4.0.0) but i still have 404 errors on project configuration tab and ekanban settings :

Started GET "/projects/test/settings" for 127.0.0.1 at 2013-03-09 11:10:47 +0100
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"test"}
  Current user: jlestel (id=71)
  Rendered projects/_form.html.erb (71.8ms)
  Rendered projects/_edit.html.erb (76.6ms)
  Rendered projects/settings/_modules.html.erb (3.5ms)
  Rendered projects/settings/_members.html.erb (132.8ms)
  Rendered projects/settings/_versions.html.erb (8.3ms)
  Rendered projects/settings/_issue_categories.html.erb (3.0ms)
  Rendered projects/settings/_wiki.html.erb (1.9ms)
  Rendered projects/settings/_repositories.html.erb (5.1ms)
  Rendered projects/settings/_activities.html.erb (22.4ms)
  Rendered plugins/ekanban/app/views/common/_tabs.html.erb (305.2ms)
  Rendered projects/settings.html.erb within layouts/base (4700.3ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.4ms)
Completed 404 Not Found in 4948ms (Views: 56.6ms | ActiveRecord: 27.6ms)

Here is the list of my local gem's :

actionmailer (3.2.12, 3.2.11)
actionpack (3.2.12, 3.2.11)
activemodel (3.2.12, 3.2.11)
activerecord (3.2.12, 3.2.11)
activerecord-mysql-adapter (0.0.1)
activerecord-mysql2-adapter (0.0.3)
activeresource (3.2.12, 3.2.11)
activesupport (3.2.12, 3.2.11)
afm (0.2.0)
arel (3.0.2)
Ascii85 (1.0.2)
autotest-rails (4.1.2)
bigdecimal (1.1.0)
builder (3.0.0)
bundler (1.3.1)
capybara (2.0.2, 1.1.4)
childprocess (0.3.9)
chronic (0.9.1)
coderay (1.0.9)
cucumber (1.2.2, 1.1.3)
cucumber-rails (1.3.0, 1.2.1)
culerity (0.2.15)
daemons (1.1.9)
database_cleaner (0.9.1)
diff-lcs (1.1.3)
erubis (2.7.0)
eventmachine (1.0.1)
eyrubygems (0.0.2)
fastercsv (1.5.5, 1.5.0)
faye-websocket (0.4.7)
ffi (1.4.0)
gherkin (2.11.6, 2.6.8)
haml (4.0.0)
hashery (2.1.0)
hike (1.2.1)
hoe (3.5.1, 1.5.1)
holidays (1.0.5, 1.0.3)
http_parser.rb (0.5.3)
i18n (0.6.4)
icalendar (1.2.2)
inifile (2.0.2)
io-console (0.3)
journey (1.0.4)
jquery-rails (2.0.3)
json (1.7.7, 1.5.5)
json_pure (1.7.7)
mail (2.4.4)
metaclass (0.0.1)
mime-types (1.21)
minitest (2.5.1)
mocha (0.12.3)
multi_json (1.6.1)
mysql (2.9.1, 2.8.1)
mysql2 (0.3.11)
net-ldap (0.3.1)
nokogiri (1.5.6)
open-uri-cached (0.0.5)
pdf-reader (1.3.2)
pg (0.14.1)
poltergeist (1.1.0, 0.6.0)
polyglot (0.3.3)
prawn (0.12.0)
rack (1.5.2, 1.4.5)
rack-cache (1.2)
rack-openid (1.3.1)
rack-ssl (1.3.3)
rack-test (0.6.2)
rails (3.2.12, 3.2.11)
railties (3.2.12, 3.2.11)
rake (10.0.3, 0.9.2.2)
rdoc (3.12.2, 3.9.5)
redgreen (1.2.2)
rmagick (2.13.2)
rspec (2.11.0, 2.5.0)
rspec-core (2.11.1, 2.5.2)
rspec-expectations (2.11.3, 2.5.0)
rspec-mocks (2.11.3, 2.5.0)
rspec-rails (2.11.4, 2.5.0)
ruby-openid (2.1.8)
ruby-prof (0.12.2)
ruby-rc4 (0.1.5)
rubyforge (2.0.4)
rubygems-bundler (1.1.1)
rubyzip (0.9.9)
rvm (1.11.3.6)
selenium-webdriver (2.31.0)
shoulda (2.11.3)
simplecov (0.7.1)
simplecov-html (0.7.1)
spork (0.9.2)
sprockets (2.2.2)
sqlite3 (1.3.7)
term-ansicolor (1.0.7)
test-unit (2.5.4, 1.2.3)
thin (1.5.0)
thor (0.17.0)
tilt (1.3.4)
timecop (0.5.9.2, 0.3.5)
treetop (1.4.12)
ttfunk (1.0.3)
tzinfo (0.3.36)
websocket (1.0.7)
xpath (1.0.0, 0.1.4)
yard (0.8.5.2)
ZenTest (4.5.0)

**Comment by samchen2009** [comment]
My successful log is as below, the only difference with you is  " Rendered plugins/ekanban/app/views/kanbans/_setup.html.haml (183.6ms)", did you have a try "bundle install“ with "gem 'haml'" in your Gemfile. Paste my Gemfile.lock here for your reference.

  Rendered projects/_form.html.erb (119.6ms)
  Rendered projects/_edit.html.erb (125.8ms)
  Rendered projects/settings/_modules.html.erb (12.7ms)
  Rendered projects/settings/_members.html.erb (463.2ms)
  Rendered projects/settings/_versions.html.erb (150.5ms)
  Rendered projects/settings/_issue_categories.html.erb (17.8ms)
  Rendered projects/settings/_wiki.html.erb (55.9ms)
  Rendered projects/settings/_repositories.html.erb (22.5ms)
  Rendered projects/settings/_activities.html.erb (186.8ms)
  Rendered plugins/ekanban/app/views/kanbans/_setup.html.haml (183.6ms)
  Rendered plugins/ekanban/app/views/common/_tabs.html.erb (1363.1ms)
  Rendered projects/settings.html.erb within layouts/base (1388.2ms)

Here is my Gemfile.lock 

GEM
  remote: http://rubygems.org/
  specs:
    actionmailer (3.2.8)
      actionpack (= 3.2.8)
      mail (~> 2.4.4)
    actionpack (3.2.8)
      activemodel (= 3.2.8)
      activesupport (= 3.2.8)
      builder (~> 3.0.0)
      erubis (~> 2.7.0)
      journey (~> 1.0.4)
      rack (~> 1.4.0)
      rack-cache (~> 1.2)
      rack-test (~> 0.6.1)
      sprockets (~> 2.1.3)
    activemodel (3.2.8)
      activesupport (= 3.2.8)
      builder (~> 3.0.0)
    activerecord (3.2.8)
      activemodel (= 3.2.8)
      activesupport (= 3.2.8)
      arel (~> 3.0.2)
      tzinfo (~> 0.3.29)
    activeresource (3.2.8)
      activemodel (= 3.2.8)
      activesupport (= 3.2.8)
    activesupport (3.2.8)
      i18n (~> 0.6)
      multi_json (~> 1.0)
    arel (3.0.2)
    builder (3.0.4)
    coderay (1.0.9)
    columnize (0.3.6)
    debugger (1.4.0)
      columnize (>= 0.3.1)
      debugger-linecache (~> 1.1.1)
      debugger-ruby_core_source (~> 1.2.0)
    debugger-linecache (1.1.2)
      debugger-ruby_core_source (>= 1.1.1)
    debugger-ruby_core_source (1.2.0)
    erubis (2.7.0)
    fastercsv (1.5.5)
    haml (4.0.0)
      tilt
    hike (1.2.1)
    i18n (0.6.4)
    journey (1.0.4)
    jquery-rails (2.0.3)
      railties (>= 3.1.0, < 5.0)
      thor (~> 0.14)
    json (1.7.7)
    mail (2.4.4)
      i18n (>= 0.4.0)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    metaclass (0.0.1)
    mime-types (1.21)
    mocha (0.12.3)
      metaclass (~> 0.0.1)
    multi_json (1.6.1)
    mysql (2.9.1)
    mysql2 (0.3.11)
    net-ldap (0.3.1)
    pg (0.14.1)
    polyglot (0.3.3)
    rack (1.4.5)
    rack-cache (1.2)
      rack (>= 0.4)
    rack-openid (1.3.1)
      rack (>= 1.1.0)
      ruby-openid (>= 2.1.8)
    rack-ssl (1.3.3)
      rack
    rack-test (0.6.2)
      rack (>= 1.0)
    rails (3.2.8)
      actionmailer (= 3.2.8)
      actionpack (= 3.2.8)
      activerecord (= 3.2.8)
      activeresource (= 3.2.8)
      activesupport (= 3.2.8)
      bundler (~> 1.0)
      railties (= 3.2.8)
    railties (3.2.8)
      actionpack (= 3.2.8)
      activesupport (= 3.2.8)
      rack-ssl (~> 1.3.2)
      rake (>= 0.8.7)
      rdoc (~> 3.4)
      thor (>= 0.14.6, < 2.0)
    rake (10.0.3)
    rdoc (3.12.2)
      json (~> 1.4)
    ruby-openid (2.1.8)
    shoulda (2.11.3)
    sprockets (2.1.3)
      hike (~> 1.2)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sqlite3 (1.3.7)
    test-unit (2.5.4)
    thor (0.17.0)
    tilt (1.3.4)
    treetop (1.4.12)
      polyglot
      polyglot (>= 0.3.1)
    tzinfo (0.3.36)
    yaml_db (0.2.3)
    yard (0.8.5.2)

PLATFORMS
  ruby

DEPENDENCIES
  activerecord-jdbcpostgresql-adapter
  activerecord-jdbcsqlite3-adapter
  builder (>= 3.0.0)
  coderay (~> 1.0.6)
  debugger (>= 1.2.0)
  fastercsv (~> 1.5.0)
  haml
  i18n (~> 0.6.0)
  jquery-rails (~> 2.0.2)
  jruby-openssl
  mocha (= 0.12.3)
  mysql
  mysql2 (~> 0.3.11)
  net-ldap (~> 0.3.1)
  pg (>= 0.11.0)
  rack-openid
  rails (= 3.2.8)
  rdoc (>= 2.4.2)
  ruby-openid (~> 2.1.4)
  shoulda (~> 2.11)
  sqlite3
  test-unit
  yaml_db
  yard

**Comment by jlestel** [comment]
I update to the last version and it works fine now.

Thanks samchen :)

**Comment by samchen2009** [comment]
Glad to hear that. Just curious, what "last version" here meant?

**Comment by jlestel** [comment]
FYI, I remove my eKanban source and i re-clone git repository.
I also add "haml" into my Gemfile.

**Comment by samchen2009** [comment]
Got it, Thanks!

**Comment by Manuel-J** [comment]
Hi,

unfortunately for me this issue seems not closed.
I have exactly the same problem

> Rendered projects/settings.html.erb within layouts/base (1847.5ms)
> Missing template, responding with 404

on my system (redmine version 2.3.0; eKaban git clone from today; haml 4.0.0; WIP Limit field created).

So how can I track this error further down, as it seems to still exist?

By the way maybe you could add a "Gemfile" with the following contents to the plugins root folder:

> source :rubygems
> gem "haml" 

This way bundle install will install haml for your plugin.

Greetings,
  Manuel

**Comment by Manuel-J** [comment]
Strange!
By restarting the whole system the problem got solved. ;)

**Comment by hastep** [comment]
I'm running version 2.2.0 of the bitnami stack and I was running into the same 404 problems reported here and in other tickets.  My problem appears to have been with the installation of haml.  The proposed _gem install haml_ didn't work.  Once I added _gem "haml"_ to /apps/redmine/htdocs/Gemfile, did a _bundle install_ and _rake redmine:plugins:migrate_ and then restarted the services, everything seems to work.

**Comment by gzbigegg** [comment]
I hit the same problem myself, it turned out to be my "production" environment caused this. Please refer to this article: http://stackoverflow.com/questions/6227945/rails-3-not-loading-haml-handler

**Comment by ghost** [comment]
@samchen2009: I have the same problem on a 2.3.1 install. This is what I do:
$ gem install haml
$ Successfully installed haml-4.0.7

Added the line
gem "haml", "~> 4.0.5"
into the Gemfile file.

$ bundle install
You are trying to install in deployment mode after changing your Gemfile. Run `bundle install` elsewhere and add the updated Gemfile.lock to version control.
If this is a development machine, remove the Gemfile freeze by running `bundle install --no-deployment`.
You have added to the Gemfile:
- haml (~> 4.0.5)
- haml (~> 4.0.5)

$ rake redmine:plugins:migrate RAILS_ENV=production
Migrating due_date_reminder (Due Date Reminder plugin)...
Migrating ekanban (Ekanban Plugin)...
Migrating redmine_auto_percent (Redmine Auto Done 100%)...
Migrating redmine_backlogs (Redmine Backlogs)...
Migrating redmine_banner (Redmine Banner plugin)...
Migrating redmine_lightbox (Redmine Light Box plugin)...
Migrating redmine_silencer (Redmine Silencer plugin)...

I then restart Apache and face the 404 error when trying to go to the Kanban  States page.

Can you help? Thanks
