### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by arunsd** [samchen2009/ekanban#51]
hi,

We have installed the redmine using bitnami and installed ekanban plugin after that
The few issues we are facing are 
1. On drag and drop from one status to another is not working. 
2. On double click there is no kanban card is shown

These two things are working in your demo.

May be we missed something to get these features. 
Appreciate your help. 

Thanks,
Arun

**Comment by prmartinuk** [comment]
Have you got Redmine running in a subfolder (e.g. http://www.example.com/Redmine )?

Due to issue #41, I had exactly the issue you describe because I had Redmine in a subfolder. You can workaround it by using the webserver's URL rewriting (mapping /kanban_apis to /redmine/kanban_apis).

**Comment by arunsd** [comment]
prmartinuk,

We are new to this. Can you please let us know where exactly we need to do this URL rewriting and its sample format.

It will save alot of time for us

Appreciate your help.

Thanks,
Arun

**Comment by prmartinuk** [comment]
I don't have a bitnami install so I am basing a lot of this off bitnami's support pages.

If you edit "installdir/apps/redmine/conf/httpd-prefix.conf" in a text editor.

You should find two lines:

```
ProxyPass /redmine balancer://redmine_cluster
ProxyPassReverse /redmine balancer://redmine_cluster
```

After those two line _ADD_ these two lines:

```
ProxyPass /kanban_apis balancer://redmine_cluster/kanban_apis
ProxyPassReverse /kanban_apis balancer://redmine_cluster/kanban_apis
```

And the restart Apache.

**Comment by arunsd** [comment]
We tried that out. Still we face the same issues
1. No kanban card is shown on double click
2. There is no status change happening on drag and drop on kanban board

Plz find the configuration below on httpd-prefix.conf

Alias /redmine/ "C:\MyApp\BitNami\redmine-2.3.2-1/apps/redmine/htdocs/public/"
Alias /redmine "C:\MyApp\BitNami\redmine-2.3.2-1/apps/redmine/htdocs/public"

ProxyPass /redmine balancer://redminecluster
ProxyPassReverse /redmine balancer://redminecluster

ProxyPass /kanban_apis balancer://redmine_cluster/kanban_apis
ProxyPassReverse /kanban_apis balancer://redmine_cluster/kanban_apis

<Proxy balancer://redminecluster>
  BalancerMember http://127.0.0.1:3001/redmine

  BalancerMember http://127.0.0.1:3002/redmine
</Proxy>

Include "C:\MyApp\BitNami\redmine-2.3.2-1/apps/redmine/conf/httpd-app.conf"

**Comment by prmartinuk** [comment]
Ah, your Redmine load balancing cluster is called redminecluster (rather than redmine_cluster)

In which case the two lines I suggested you add should have read:

```
ProxyPass /kanban_apis balancer://redminecluster/kanban_apis
ProxyPassReverse /kanban_apis balancer://redminecluster/kanban_apis
```

and then restart apache.

**Comment by arunsd** [comment]
prmartinuk,

Sorry about that. We corrected it and Now its working. Let us check all cases and if we notice some issues, we will get back to you. You guys are doing a really good work, especially very fast responses
Thanks alot.
Really appreciate your time and support

Arun

**Comment by banterCZ** [comment]
I am using bitnami with Redmine 2.3.3-0. I edited `httpd-prefix.conf` as you suggest but I get the following error during Apache start:

> Syntax error on line 10 of /home/banter/redmine-2.3.3-0/apps/redmine/conf/httpd-prefix.conf: BalancerMember must define remote proxy server
