### ISSUE TITLE
error 404 not found when saving a kanban state (missing folder in url) and Internal error when trying to view kanbans in a project

### ISSUE THREAD

**Issue by KoenBoone** [samchen2009/ekanban#6]
When I try to save a kanban state in admin, i end up with an error 404 and I notice the subfolder is missing.
My bitnami redmine (on windows) runs under http://domain/redmine
When saving the state, it goes to http://domain//kanban_states/setup?tab=Stages instead of  http://domain/redmine/kanban_states/setup?tab=Stages

also, when trying the view the kanbans for a project, I get a internal error :-(

Everything else works perfectly under this /redmine folder.  could it be there is somewhere a static notation of the location in your code?

thanks in advance!

**Comment by samchen2009** [comment]
Did you install the gem 'haml' ? If yes, please attach the log and more information like redmine version, Gemfile.lock, plugins you have installed,  etc ... But most likely, it's caused by 'haml'.

**Comment by KoenBoone** [comment]
Yes I installed haml, manually and also included it in the gemfile.

I had this problem on 2.1.3, and then decided to do an upgrade of my bitnami redmine stack tot 2.2.3 and the problem was still there, but I then also had some other problems like not being able to edit issues, so I'm now reverting back to a backup, and will revisit this in the near future when I have a little more time :-(

Thanks for your quick reply though!

Here's my info for your review, maybe there is something there...:

Bitnami Redmine stack 2.1.3 and 2.2.3 on Windows 2003

The following is from the 2.2.3 stack, the plugin situation was the same for both versions.
GEMFILE:

```
source 'http://rubygems.org'

gem "thin"
gem "haml"

gem 'rails', '3.2.12'
gem "jquery-rails", "~> 2.0.2"
gem "i18n", "~> 0.6.0"
gem "coderay", "~> 1.0.6"
gem "fastercsv", "~> 1.5.0", :platforms => [:mri_18, :mingw_18, :jruby]
gem "builder", "3.0.0"

# Optional gem for LDAP authentication
group :ldap do
  gem "net-ldap", "~> 0.3.1"
end

# Optional gem for OpenID authentication
group :openid do
  gem "ruby-openid", "~> 2.1.4", :require => "openid"
  gem "rack-openid"
end

# Optional gem for exporting the gantt to a PNG file, not supported with jruby
platforms :mri, :mingw do
  group :rmagick do
    # RMagick 2 supports ruby 1.9
    # RMagick 1 would be fine for ruby 1.8 but Bundler does not support
    # different requirements for the same gem on different platforms
    gem "rmagick", ">= 2.0.0"
  end
end

# Database gems
platforms :mri, :mingw do
  group :postgresql do
    #gem "pg", ">= 0.11.0"
  end

  group :sqlite do
    gem "sqlite3"
  end
end

platforms :mri_18, :mingw_18 do
  group :mysql do
    #gem "mysql", "~> 2.8.1"
  end
end

platforms :mri_19, :mingw_19 do
  group :mysql do
    gem "mysql2", "~> 0.3.11"
  end
end

platforms :jruby do
  gem "jruby-openssl"

  group :mysql do
    gem "activerecord-jdbcmysql-adapter"
  end

  group :postgresql do
    gem "activerecord-jdbcpostgresql-adapter"
  end

  group :sqlite do
    gem "activerecord-jdbcsqlite3-adapter"
  end
end

group :development do
  gem "rdoc", ">= 2.4.2"
  gem "yard"
end

group :test do
  #gem "shoulda", "~> 2.11"
  # Shoulda does not work nice on Ruby 1.9.3 and JRuby 1.7.
  # It seems to need test-unit explicitely.
  platforms = [:mri_19]
  platforms << :jruby if defined?(JRUBY_VERSION) && JRUBY_VERSION >= "1.7"
  gem "test-unit", :platforms => platforms
  gem "mocha", "0.12.3"
end

local_gemfile = File.join(File.dirname(__FILE__), "Gemfile.local")
if File.exists?(local_gemfile)
  puts "Loading Gemfile.local ..." if $DEBUG # `ruby -d` or `bundle -v`
  instance_eval File.read(local_gemfile)
end

# Load plugins' Gemfiles
Dir.glob File.expand_path("../plugins/*/Gemfile", __FILE__) do |file|
  puts "Loading #{file} ..." if $DEBUG # `ruby -d` or `bundle -v`
  instance_eval File.read(file)
end
```

My Gemfile.lock file

```
GEM
  remote: http://rubygems.org/
  specs:
    actionmailer (3.2.12)
      actionpack (= 3.2.12)
      mail (~> 2.4.4)
    actionpack (3.2.12)
      activemodel (= 3.2.12)
      activesupport (= 3.2.12)
      builder (~> 3.0.0)
      erubis (~> 2.7.0)
      journey (~> 1.0.4)
      rack (~> 1.4.5)
      rack-cache (~> 1.2)
      rack-test (~> 0.6.1)
      sprockets (~> 2.2.1)
    activemodel (3.2.12)
      activesupport (= 3.2.12)
      builder (~> 3.0.0)
    activerecord (3.2.12)
      activemodel (= 3.2.12)
      activesupport (= 3.2.12)
      arel (~> 3.0.2)
      tzinfo (~> 0.3.29)
    activeresource (3.2.12)
      activemodel (= 3.2.12)
      activesupport (= 3.2.12)
    activesupport (3.2.12)
      i18n (~> 0.6)
      multi_json (~> 1.0)
    arel (3.0.2)
    builder (3.0.0)
    coderay (1.0.6)
    daemons (1.1.8)
    erubis (2.7.0)
    eventmachine (1.0.0-x86-mingw32)
    fastercsv (1.5.4)
    haml (4.0.0)
      tilt
    hike (1.2.1)
    i18n (0.6.0)
    journey (1.0.4)
    jquery-rails (2.0.3)
      railties (>= 3.1.0, < 5.0)
      thor (~> 0.14)
    json (1.7.7)
    mail (2.4.4)
      i18n (>= 0.4.0)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    metaclass (0.0.1)
    mime-types (1.19)
    mocha (0.12.3)
      metaclass (~> 0.0.1)
    multi_json (1.3.6)
    mysql2 (0.3.11-x86-mingw32)
    net-ldap (0.3.1)
    polyglot (0.3.3)
    rack (1.4.5)
    rack-cache (1.2)
      rack (>= 0.4)
    rack-openid (1.3.1)
      rack (>= 1.1.0)
      ruby-openid (>= 2.1.8)
    rack-ssl (1.3.2)
      rack
    rack-test (0.6.1)
      rack (>= 1.0)
    rails (3.2.12)
      actionmailer (= 3.2.12)
      actionpack (= 3.2.12)
      activerecord (= 3.2.12)
      activeresource (= 3.2.12)
      activesupport (= 3.2.12)
      bundler (~> 1.0)
      railties (= 3.2.12)
    railties (3.2.12)
      actionpack (= 3.2.12)
      activesupport (= 3.2.12)
      rack-ssl (~> 1.3.2)
      rake (>= 0.8.7)
      rdoc (~> 3.4)
      thor (>= 0.14.6, < 2.0)
    rake (0.9.2.2)
    rdoc (3.12)
      json (~> 1.4)
    rmagick (2.13.1)
    ruby-openid (2.1.8)
    sprockets (2.2.1)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sqlite3 (1.3.6-x86-mingw32)
    thin (1.3.1)
      daemons (>= 1.0.9)
      eventmachine (>= 0.12.6)
      rack (>= 1.0.0)
    thor (0.15.4)
    tilt (1.3.3)
    treetop (1.4.10)
      polyglot
      polyglot (>= 0.3.1)
    tzinfo (0.3.33)
    yard (0.8.1)

PLATFORMS
  x86-mingw32

DEPENDENCIES
  activerecord-jdbcmysql-adapter
  activerecord-jdbcpostgresql-adapter
  activerecord-jdbcsqlite3-adapter
  builder (= 3.0.0)
  coderay (~> 1.0.6)
  fastercsv (~> 1.5.0)
  haml
  i18n (~> 0.6.0)
  jquery-rails (~> 2.0.2)
  jruby-openssl
  mocha (= 0.12.3)
  mysql2 (~> 0.3.11)
  net-ldap (~> 0.3.1)
  rack-openid
  rails (= 3.2.12)
  rdoc (>= 2.4.2)
  rmagick (>= 2.0.0)
  ruby-openid (~> 2.1.4)
  sqlite3
  test-unit
  thin
  yard
```

Installed plugins:

```
- extended fields 0.2.0b
- progressive Projects list plugin 0.2.0
- redmine banner plugin 0.0.8
- did you mean? 2.0.1
- redmine issue checklist plugin 2.0.3
- redmine open links in new window plugin 0.0.3
- redmine stealth plugin 0.6.0
```

I also had these plugins installed but uninstalled them because they where not used or did not work as I thought they would:

```
- AgileDwarf
- Latest_issues
- redmine textilizable custom fields
```

**Comment by samchen2009** [comment]
No clue yet, but you can have a check https://github.com/samchen2009/ekanban/issues/5 to see whether it's a similar issue.

**Comment by KoenBoone** [comment]
Hi,
No, not quite similar.  I did have this error as well at first, but then noticed haml wasn't installed correctly so reinstalled haml and then those issues as in #5 where fixed.
Then I could access the admin and the project settings, but the problems I described here popped up. :-(
I am going to try to make time this weekend to reinstall redmine 2.3.3, reimport my data and the ekanban plugin in a  new virtual machine.  Maybe I did something wrong with the upgrade earlier... (althoug on 2.1.3 I'm having the same problem)...
Still think it might have something to do with the fact that the bitnami redmine on windows is hosted in the /redmine subfolder, I'm having the same problem with the plugin 'latest_issues' which I removed because of that.... because the other ekanban pages do work as they should?
I'll keep you posted...

**Comment by KoenBoone** [comment]
I gave it another go today, and ran into some other problems first, like in #7 but fixed that.

Still, I am having the same error pages as before :-(
and Haml is installed.

I'm gonna take another crack at it tomorrow though, but I still think it's a location issue because of the subfolder bitnami redmine is hosted under?

Also, now when I try to add a comment to an issue I also get an errorpage

**Comment by KoenBoone** [comment]
Also for your info the error message from the log....

No error is visible in the log for the kanban error (seems logical as it is a 404 eror) but here's the error I get when trying to add a comment to an issue (this only happens when the ekanban plugin is installed with haml)

```
Started PUT "/redmine/issues/1205" for 178.116.220.5 at 2013-03-16 21:23:26 +0100
Processing by IssuesController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"wLA0LRlRlkYybkNaZR6VrF0pn9PR7V8/3eLJUSQEsVU=", "issue"=>{"is_private"=>"0", "project_id"=>"21", "tracker_id"=>"4", "subject"=>"test", "description"=>"test", "status_id"=>"1", "priority_id"=>"4", "assigned_to_id"=>"1", "fixed_version_id"=>"", "parent_issue_id"=>"", "start_date"=>"2013-03-16", "due_date"=>"", "estimated_hours"=>"", "done_ratio"=>"0", "custom_field_values"=>{"2"=>"0", "19"=>"", "21"=>"", "4"=>"", "5"=>"", "26"=>"", "27"=>"1"}, "notes"=>"test", "private_notes"=>"0", "lock_version"=>"1"}, "new_checklist"=>"", "time_entry"=>{"hours"=>"", "activity_id"=>"", "comments"=>""}, "attachments"=>{"1"=>{"description"=>""}}, "last_journal_id"=>"12031", "commit"=>"Submit", "id"=>"1205"}
  Current user: koen@itakasper.be (id=1)
  Rendered mailer/_issue.text.erb (0.0ms)
  Rendered mailer/issue_edit.text.erb within layouts/mailer (15.6ms)
  Rendered mailer/_issue.html.erb (15.6ms)
  Rendered mailer/issue_edit.html.erb within layouts/mailer (31.3ms)
Completed 500 Internal Server Error in 1031ms

TypeError (can't dup NilClass):
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  app/models/issue.rb:967:in `block in save_issue_with_child_records'
  app/models/issue.rb:952:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:176:in `update'
```

**Comment by KoenBoone** [comment]
looks like this might be kind of the same problem as in #9 and #10?
I'll check out the concerning field in the db this evening...

**Comment by KoenBoone** [comment]
I had another go at it, but still having the same errors when editing an issue or creating a new issue. And also the 404 errors which may be bitnami related because of the /redmine subfolder it's hosted under...

The plugin looks really promising and seems to be exactly what we need, but I do not have time at the moment to dig into this so I'm just gonna wait and check here periodically to see if this is resolved in the future.

Looks like you are actively working on this plugin, so I'm hopefull :-)

**Comment by q22** [comment]
There is a typo in the instructions for creating the custom field. The "Add a field "WIP Limit" is spelled with an uppercase "L", but in the file app/models/kanban_pane.rb, it is actually "WIP limit" with a lowercase "l".  

When I modified the custom field to be "WIP limit" with a lower case "l" - the 404 issues went away, and everything is working fine so far.

**Comment by KoenBoone** [comment]
thanks, hmm, could it really be so simple?  I'm gonna have to try again in a few days...

**Comment by samchen2009** [comment]
q22, thank you so much to figure it out. I'll update the instruction. Sorry for the inconvenience ...

**Comment by KoenBoone** [comment]
well, changing WIP Limit to WIP limit did indeed fix some errors, but I still have other errors when creating an issue, when updating an issue that was created before ekanban was installed, and the kanban panes do not work because it can not load the ekanban api files due to the bitnami setup being hosted under the /redmine folder url.

I guess I'll have to restrict myself to using plugins that have no problem with relative urls, luckely that's nearly all of them.  I'll check back in the future to see if this is fixed...

I don't 'speak' ruby, but i've created a sort of standalone kanban system which just accesses the rest api to do the changes... it works for now so i'm not urgently in need of this plugin anymore  :-)

**Comment by tjaehnel** [comment]
I fixed a similar issue by installing haml 3.1.8
Gemfile entry: gem "haml", "3.1.8"
Seems they did some incompatible changes in 4.0.

Toby

**Comment by KoenBoone** [comment]
gonna give this another try

**Comment by KoenBoone** [comment]
nah, giving up, too many problems + it only works for newly created issues :-(
