### ISSUE TITLE
 ERROR:  column "wip_limit" cannot be cast to type boolean

### ISSUE THREAD

**Issue by thanakrit** [samchen2009/ekanban#63]
Hi, 

(Sorry in my english)
I setup plugin on redmine 2.3.3 and the error is appear.

PG::DatatypeMismatch: ERROR:  column "wip_limit" cannot be cast to type boolean
: ALTER TABLE "kanban_panes" ALTER COLUMN "wip_limit" TYPE boolean/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `async_exec'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in`execute'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `log'
/var/lib/gems/1.8/gems/activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:649:in`execute'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:1030:in `change_column'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:466:in`send'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:466:in `method_missing'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:438:in`say_with_time'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:438:in `say_with_time'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:458:in`method_missing'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:334:in `send'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:334:in`method_missing'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:370:in `up'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:410:in`send'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:410:in `migrate'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:410:in`migrate'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:389:in`migrate'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:528:in `__send__'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:528:in`migrate'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:720:in `migrate'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:775:in`call'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:775:in `ddl_transaction'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in`transaction'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/transactions.rb:208:in `transaction'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:775:in`ddl_transaction'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:719:in `migrate'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:700:in`each'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:700:in `migrate'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:570:in`up'
/var/lib/gems/1.8/gems/activerecord-3.2.13/lib/active_record/migration.rb:551:in `migrate'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

and the i follow the instruction 

Add a field "WIP limit" (format:integer) in 'Administrator' -> 'Custom fields' -> 'User'    

Redmine information
Environment:
  Redmine version                2.3.3.stable
  Ruby version                   1.8.7-p352 (2011-06-30) [x86_64-linux]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               PostgreSQL
Redmine plugins:
  ekanban                        0.0.1
  redmine_banner                 0.0.9
  redmine_code_review            0.6.3
  redmine_issue_checklist        2.0.5
  redmine_questions              0.0.5
  redmine_tags                   2.0.1-dev

**Comment by prmartinuk** [comment]
Are you trying to install or uninstall ekanban?

You used to get that error if you were trying to uninstall ekanban.

**Comment by samchen2009** [comment]
You're using PostgreSQL,right? See issue #7 and try chupacabras's comment.

**Comment by thanakrit** [comment]
Thank you samchen2009

**Comment by thanakrit** [comment]
hi samchen2009,
after i uninstall and reinstall  plugin  the error not appear, but when i access the project setting error 
![screen shot 2013-10-23 at 12 23 15 am](https://f.cloud.github.com/assets/47860/1383508/abdc56ae-3b3e-11e3-9786-c2dbef45088b.png) it appear and can not access project setting.

log file

Started GET "/redmine/projects/fio-2/settings" for 27.55.223.179 at Wed Oct 23 00:14:59 +0700 2013
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"fio-2"}
  Current user: thanakrit (id=4)
  Rendered projects/_form.html.erb (98.7ms)
  Rendered projects/_edit.html.erb (100.3ms)
  Rendered projects/settings/_modules.html.erb (4.4ms)
  Rendered projects/settings/_members.html.erb (27.3ms)
  Rendered projects/settings/_versions.html.erb (5.7ms)
  Rendered projects/settings/_issue_categories.html.erb (2.7ms)
  Rendered projects/settings/_wiki.html.erb (1.8ms)
  Rendered projects/settings/_repositories.html.erb (2.5ms)
  Rendered projects/settings/_boards.html.erb (2.6ms)
  Rendered projects/settings/_activities.html.erb (98.7ms)
  Rendered plugins/ekanban/app/views/common/_tabs.html.erb (255.8ms)
  Rendered projects/settings.html.erb within layouts/base (256.9ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.2ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (0.1ms)
  Rendered plugins/redmine_banner/app/views/banner/_project_body_bottom.html.erb (0.1ms)
  Rendered plugins/redmine_banner/app/views/banner/_body_bottom.html.erb (3.8ms)
  Rendered plugins/redmine_banner/app/views/banner/_after_top_menu.html.erb (4.1ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.1ms)
Completed 404 Not Found in 295ms (Views: 21.3ms | ActiveRecord: 16.6ms)

**Comment by thanakrit** [comment]
install success  thank you
