### ISSUE TITLE
DB error (in installing)

### ISSUE THREAD

**Issue by whatwant** [samchen2009/ekanban#7]
rake redmine:plugins:migrate RAILS_ENV=production

<pre>
-- add_column(:kanbans, :description, :text, {:limit=>256})
rake aborted!
An error has occurred, this and all later migrations canceled:

PG::Error: 오류:  "text" 형식에는 형식 한정자를 사용할 수 없음
LINE 1: ALTER TABLE "kanbans" ADD COLUMN "description" text(256)
                                                       ^
: ALTER TABLE "kanbans" ADD COLUMN "description" text(256)
</pre>

MY Environment

<pre>
Environment:
  Redmine version                          2.2.3.stable
  Ruby version                             1.9.2 (x86_64-linux)
  Rails version                            3.2.12
  Environment                              production
  Database adapter                         PostgreSQL
</pre>

**Comment by samchen2009** [comment]
Only verified on sqlite3 and mysql, is it possible to translate "PG::Error: 오류:  "text" 형식에는 형식 한정자를 사용할 수 없음" to english?

**Comment by KoenBoone** [comment]
I had the same problem when retrying to install this plugin, also a db error where I got the message that a table did not exist.
For me this was because I had already tried to install the plugin earlier and did an uninstall with VERSION=0 and then afterwards removed the tables by hand because they where still there.
This did however left some records in the table 'schema_migrations'.  
I removed every record for ekanban from this table and then could install/migrate the plugin without errors.

Maybe this is also a sollution in this case?

**Comment by KoenBoone** [comment]
oh and, according to google translate, the translation (Korean?) is: Error: "text" format type qualifier can not be used :-)

**Comment by chupacabras** [comment]
you have to modify scripts in db/migrate folder.
006_create_kanban_workflows.rb
change:
t.boolean :check_wip_limit

010_add_kanban_tables_options.rb
remove lines:
change_column :kanban_panes, :wip_limit, :boolean, :default => 1, :null => false
change_column :kanban_workflows, :check_wip_limit, :boolean, :default => true

and in all scripts in this folder remove ":limit => 128" option from lines related to ":text" type.

after this you will be able to install this plugin to postgresql db.

**Comment by whatwant** [comment]
install success..... (thank u  chupacabras)

and then, Setup Kanban States
and then, Go to "Project" -> "Kanban" and click "New Kanban"........ error !!!!!!

<pre>
Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.
If you are the Redmine administrator, check your log files for details about the error.
Back
</pre>

log file....

<pre>
Started GET "/redmine/projects/test/kanbans" for 168.219.61.202 at 2013-03-20 10:14:28 +0900
Processing by KanbansController#index as HTML
  Parameters: {"project_id"=>"test"}
  Current user: jk7744.park (id=3)
  Rendered plugins/ekanban/app/views/kanbans/index.html.haml within layouts/base (84.4ms)
Completed 500 Internal Server Error in 290ms
ActionView::Template::Error (undefined method `id' for nil:NilClass):
    2:   %span Your current wip:
    3:   = link_to "#{User.current.wip} ", my_page_path(), :id => "my-wip"
    4:   %span  Limit:
    5:   = link_to "#{User.current.wip_limit} ", edit_user_path(User.current.id), :id => "my-wip-limit"
    6:   = link_to l(:label_kanban_new), new_project_kanban_path(@project.id), :class => 'icon icon-add'
    7: %h2 Kanbans
    8:
  plugins/ekanban/app/models/kanban.rb:283:in `wip_limit'
  plugins/ekanban/app/views/kanbans/index.html.haml:5:in `_plugins_ekanban_app_views_kanbans_index_html_haml__45157085$
  actionpack (3.2.12) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.12) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.12) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.12) lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
...
</pre>

**Comment by chupacabras** [comment]
i think that error message is discussed in another issue.

**Comment by samchen2009** [comment]
Thanks Chupacabras! 
BTW, the "WIP Limit" is solved at #10, also update the Readme.md.

**Comment by whatwant** [comment]
Thanks everyone !!!
