### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by jlestel** [samchen2009/ekanban#8]
Hello,

Could you create a user documentation in order to explain eKanban configuration and projects configuration needed to initialize a Kanban process ?

Because, I try to use your plugin but i can't find the way to display a Kanban tasks board.

Thanks :)

**Comment by markedagain** [comment]
u need to set the proper view permissions from global permissions for roles

**Comment by jlestel** [comment]
Ok, i find the way to configure issue statuses and Kanban states to display a valid Kanban.

Thx

**Comment by samchen2009** [comment]
Some paragraphs were added in the Readme.md, hope it's helpful to you.

**Comment by jlestel** [comment]
Yes, this paragraphs have been very helpful !

Thanks !
