### ISSUE TITLE
"Kanbans" menu entry missing for regular users (non-admins)

### ISSUE THREAD

**Issue by RafiKueng** [samchen2009/ekanban#82]
I have a fresh install of 2.5.2 with the current ekanban.
I setup a new project. If I login as admin, I see the tab "Kanbans" in the menu, as a regular user. I don't see this menu entry. I made sure the module is activated (under project > settings > Modules). Under project > settings > kanban I do have an active Kanban listed. I can manually go to the page by manually typing the url like http://redmine/projects/test/kanbans

What am I doing wrong, or could this be a bug?

I'm new to redmine, please let me know if you need further information to help to find the bug.

**Comment by prmartinuk** [comment]
It sounds like you need to give the regular users permission to view the Kanbans.

If you go to the Administration pages of Redmine, under "Roles and permissions" select the Role that your users have for your new project. Near the top of the list of different permissions, you will have a "Kanban" section where you need to enable the "View kanban" option.

**Comment by RafiKueng** [comment]
Hmm that one's on me, I'm sorry... Don't mind this issue please :)
@prmartinuk Thank you very much for the help!
